name: Gradle Build
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and initialize Thunder submodule
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Initialize JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set executable flag on gradle
      run: chmod +x ./gradlew
    - name: Gradle build robot application
      run: ./gradlew build
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
