name: Java Linter
on: [push, pull_request]
jobs:
  linter:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - name: Checkout repository and initialize Thunder submodule
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

